// Independent ZPROP tool catalogue.
window.ZPROP_TOOLS = [
  {id:'bio-pages',icon:'▣',name:['Halaman bio','Bio pages'],tag:['IDENTITI DIGITAL','DIGITAL IDENTITY'],title:['Semua tentang anda. Satu halaman.','Everything about you. One page.'],description:['Bina halaman bio dengan pautan, teks dan imej. Susun blok anda dan lihat perubahan secara langsung.','Build a bio page with links, text and images. Arrange your blocks and see every change live.'],features:[['Tambah dan susun blok kandungan','Add and arrange content blocks'],['Muat naik foto dan imej','Upload photos and images'],['Pratonton langsung dan penerbitan','Live preview and publishing']],availability:['','']},
  {id:'short-links',icon:'↗',name:['Pautan pendek','Short links'],tag:['PAUTAN YANG MUDAH DIINGATI','MEMORABLE LINKS'],title:['Pautan panjang. Nama yang ringkas.','Long links. A simpler name.'],description:['Cipta pautan ringkas yang membawa pelawat terus ke URL destinasi anda.','Create a short link that takes visitors directly to your destination URL.'],features:[['Pilih nama pautan sendiri','Choose your own link name'],['Simpan pautan pada pelayan','Save your link on the server'],['Salin dan buka pautan anda','Copy and open your link']],availability:['Cipta dan kongsi pautan pendek anda di zprop.tech.','Create and share your short links on zprop.tech.']},
  {id:'transfer-files',icon:'⇧',name:['Pautan fail','File link'],tag:['FAIL ANDA, SATU PAUTAN','YOUR FILE, ONE LINK'],title:['Tukar fail anda kepada pautan.','Turn your file into a link.'],description:['Muat naik PDF atau Excel, pilih nama pautan dan buka fail terus melalui pautan anda.','Upload a PDF or Excel file, choose a link name and access your file directly through its link.'],features:[['Muat naik PDF atau Excel','Upload a PDF or Excel file'],['Pilih nama pautan unik','Choose a unique link name'],['Buka, edit atau salin pautan','Open, edit or copy the link']],availability:['Kongsi PDF dan Excel melalui pautan zprop.tech anda.','Share PDFs and Excel files with your zprop.tech link.']},
  {id:'vcards',icon:'♙',name:['Kongsi vCard','Share vcards'],tag:['HUBUNGAN YANG LEBIH DEKAT','CLOSER CONNECTIONS'],title:['Perkenalan yang terus disimpan.','An introduction worth saving.'],description:['Hasilkan kad kenalan digital supaya pelanggan boleh menyimpan maklumat anda ke dalam telefon.','Create a digital contact card so clients can save your details on their phone.'],features:[['Nama, syarikat, telefon dan e-mel','Name, company, phone and email'],['Format vCard standard (.vcf)','Standard vCard format (.vcf)'],['Muat turun dan kongsi sendiri','Download and share directly']],availability:['Simpan vCard secara peribadi dalam akaun anda, kemudian muat turun untuk dikongsi.','Save vCards privately to your account, then download them to share.']},
  {id:'host-html',icon:'⌘',name:['Laman statik','Static site'],tag:['DARIPADA FAIL KEPADA LAMAN WEB','FROM FILES TO A WEBSITE'],title:['Laman web anda. Sedia dalam sekelip mata.','Your website. Ready in moments.'],description:['Muat naik fail HTML atau ZIP, atau tampal kod anda. Cipta laman statik dengan pautan tersendiri.','Upload an HTML or ZIP file, or paste your code. Create a static website with a link of its own.'],features:[['Muat naik HTML atau ZIP','HTML or ZIP upload'],['Tampal kod HTML anda','Paste your HTML'],['Pilih URL ringkas sendiri','Choose a custom short URL']],availability:['HTML, CSS dan JavaScript statik disokong. Laman dijalankan dalam ruang berasingan tanpa akses kepada dashboard.','Static HTML, CSS and JavaScript are supported. Sites run in isolation from the dashboard.']},
  {id:'qr-codes',icon:'▦',name:['Kod QR','QR Codes'],tag:['IMBAS DAN TERUS BERHUBUNG','SCAN AND CONNECT'],title:['Cipta kod QR anda.','Create your QR code.'],description:['Jadikan pautan, perbualan, lokasi, acara dan kad kenalan anda mudah diakses dengan satu imbasan.','Make your links, conversations, locations, events and contact cards accessible with one scan.'],features:[['URL, WhatsApp, Location, Event dan Vcard','URL, WhatsApp, Location, Event and Vcard'],['Pratonton selepas kod dicipta','Preview after creating your code'],['Muat turun PNG dan SVG','Download PNG and SVG']],availability:['Kod QR disimpan dalam akaun anda untuk diedit atau dipadam kemudian. Muat turun PNG atau SVG untuk dikongsi.','QR codes are saved in your account to edit or delete later. Download PNG or SVG to share.']},
];
