(() => {
  const copy = {
    phoneBackLabel:['LAMAN STATIK ANDA','YOUR STATIC SITE'], phoneBackTitle:['Idea anda.<br>Kini dalam talian.','Your idea.<br>Now a website.'], phoneReady:['Laman anda sedia','Your site is ready'], phoneTitle:['Idea anda.<br>Ruang anda.','Your ideas.<br>Your space.'], phoneSubtitle:['Satu pautan. Pelbagai kemungkinan.','One link. So many possibilities.'], phoneBio:['Bina halaman bio','Build a bio page'], phoneLinks:['Cipta pautan pendek','Create a short link'], phoneFooter:['Langkah seterusnya bermula di sini.','Your next chapter starts here.'], phoneCaption:['Identiti sendiri. Ruang milik anda.','Your own identity. Your own space.'],
    badge:['RUANG KERJA DIGITAL ANDA','YOUR DIGITAL WORKSPACE'], title:['Satu tempat.<br><span>Semua alatan anda.</span>','One place.<br><span>All your tools.</span>'], intro:['Daripada idea kepada laman web. Cipta halaman, sediakan pautan dan urus kerja harian anda dengan alatan khusus.','From an idea to a website. Create pages, prepare links and take care of everyday tasks with a tool for each job.'], create:['Cipta laman statik','Create a static site'], tools:['Pilih alatan anda.','Choose your tool.'], count:['06 ALATAN · SATU RUANG KERJA','06 TOOLS · ONE WORKSPACE'], guideTag:['MUDAH UNTUK BERMULA','SIMPLE FROM THE START'], guideTitle:['Fail anda. Laman web anda.','Your files. Your website.'], step1:['Tambah kandungan','Add your content'], step1Text:['Muat naik HTML atau ZIP dengan index.html, atau tampal HTML terus dalam editor.','Upload HTML or a ZIP with index.html, or paste HTML directly into the editor.'], step2:['Jadikan milik anda','Make it yours'], step2Text:['Pilih nama URL ringkas atau biarkan kami menjana satu untuk anda.','Choose a short URL name or leave it empty and we will generate one for you.'], step3:['Cipta dan buka','Create and open'], step3Text:['Cipta laman, semak pratonton dan kongsi pautan zprop.tech anda.','Create your site, check the preview and share your zprop.tech link.'], faq1:['Apakah fail yang boleh dimuat naik?','What files can I upload?'], faq1Text:['Fail HTML atau ZIP sehingga 256 MB. ZIP perlu mengandungi index.html dan aset statik dengan laluan relatif.','An HTML or ZIP file up to 256 MB. ZIPs need an index.html and static assets referenced with relative paths.'], faq2:['Bolehkah saya berkongsi pautan laman?','Can I share my site link?'], faq2Text:['Ya. Cipta laman anda, kemudian salin pautan zprop.tech untuk dikongsi. Pelawat tidak perlu log masuk untuk membukanya.','Yes. Create your site, then copy its zprop.tech link to share. Visitors can open it without signing in.']
  };
  copy.title = ['Satu tempat.<br>Lebih banyak<br><span>kemungkinan.</span>', 'One place.<br>More possibilities.<br><span>Your ZPROP.</span>'];
  function localize() {
    const language = document.documentElement.lang === 'en' ? 1 : 0;
    document.title = language ? 'Your tools — ZPROP' : 'Alatan anda — ZPROP';
    document.querySelector('meta[name="description"]').content = copy.intro[language];
    document.querySelectorAll('[data-dashboard-copy]').forEach(el => el.innerHTML = copy[el.dataset.dashboardCopy][language]);
    document.querySelectorAll('[data-dashboard-description]').forEach(el => el.textContent = window.ZPROP_TOOLS.find(tool => tool.id === el.dataset.dashboardDescription).description[language]);
  }
  document.addEventListener('zprop:language', localize); localize();
  window.ZpropLanguage?.ready();
})();
