const {test,expect}=require('./auth-fixture');
const {createBio,addBlock}=require('./bio-helper');
const fs=require('node:fs/promises');

test('social setup adds three clickable footer circles that persist in templates, downloads and published pages',async({page,request,baseURL},info)=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  const slug=await createBio(page);
  await expect(page.locator('#bio-preview .bio-social-circle')).toHaveCount(3);
  await page.locator('[data-tab=appearance]').click();
  await expect(page.locator('[data-template] .bio-template-social svg')).toHaveCount(27);
  await page.locator('[data-template=rose]').click();
  await page.locator('#bio-preview [data-setup-social="1"]').click();
  const form=page.locator('#block-details-form');
  await expect(form).toBeVisible();
  await page.locator('#confirm-add-block').click();
  await expect(page.locator('[data-block-type=social]')).toHaveCount(0);
  await expect(form.locator('[name=url1]')).toBeFocused();
  for(const value of ['javascript:alert(1)','https://user:pass@example.com']) {
    await form.locator('[name=url1]').fill(value);await page.locator('#confirm-add-block').click();
    await expect(page.locator('[data-block-type=social]')).toHaveCount(0);
  }
  for(const slot of [1,2,3])await form.locator('[name=url'+slot+']').fill(baseURL+'/landing.html?social='+slot);
  await form.locator('[name=platform3]').selectOption('youtube');
  await page.locator('#confirm-add-block').click();
  await expect(page.locator('#block-picker')).toBeHidden();
  const social=page.locator('[data-block-type=social]');
  await expect(social.locator('.bio-block-fields')).toBeHidden();
  await expect(page.locator('.bio-page-social a')).toHaveCount(3);
  await expect(page.locator('.bio-page-social a').nth(2)).toHaveAccessibleName('YouTube');
  await expect(page.locator('.bio-page-social a').first()).toHaveCSS('border-radius','50%');
  const popupPromise=page.waitForEvent('popup');
  await page.locator('.bio-page-social a').first().click();
  const popup=await popupPromise;await expect(popup).toHaveURL(baseURL+'/landing.html?social=1');await popup.close();
  await page.locator('[data-tab=content]').click();
  await expect(social.locator('[data-block-action=duplicate]')).toBeDisabled();
  await page.locator('#add-block').click();await expect(page.locator('[data-add=social]')).toBeDisabled();await page.keyboard.press('Escape');
  await addBlock(page,'heading',{heading:'My latest work'});
  await social.locator('.bio-drag-handle').focus();await page.keyboard.press('ArrowUp');
  expect(await page.locator('.bio-page-social').evaluate(el=>el.previousElementSibling.classList.contains('bio-page-blocks'))).toBe(true);
  await page.locator('#save-bio-draft').click();await expect(page.locator('#tool-status')).toHaveText('Draft saved.');
  await page.reload();await expect(page.locator('.bio-page-social a')).toHaveCount(3);
  await expect(social.locator('.bio-block-fields')).toBeHidden();
  await page.locator('[data-tab=appearance]').click();await page.locator('[data-template=midnight]').click();
  await expect(page.locator('.bio-page-social a').first()).toHaveCSS('background-color','rgb(191, 202, 255)');
  await expect(page.locator('.bio-page-social a').first()).toHaveAttribute('href',baseURL+'/landing.html?social=1');
  await page.locator('#publish-bio').click();await expect(page.locator('#bio-result')).toBeVisible();
  const html=await (await request.get('/sites/'+slug+'/')).text();
  expect(html).toContain('aria-label="YouTube"');expect(html).not.toContain('data-setup-social');
  expect(html.indexOf('<nav class="bio-page-social"')).toBeGreaterThan(html.indexOf('My latest work'));
  const downloadPromise=page.waitForEvent('download');await page.locator('[data-action=downloadHtml]').click();
  expect(await fs.readFile(await (await downloadPromise).path(),'utf8')).toBe(html);
  const publicPage=await page.context().newPage();await publicPage.goto('/sites/'+slug+'/');
  const publicPopupPromise=publicPage.waitForEvent('popup');await publicPage.getByRole('link',{name:'YouTube',exact:true}).click();
  const publicPopup=await publicPopupPromise;await expect(publicPopup).toHaveURL(baseURL+'/landing.html?social=3');await publicPopup.close();await publicPage.close();
  await page.locator('.bio-templates').scrollIntoViewIfNeeded();
  await page.screenshot({path:'test-results/bio-social-'+info.project.name+'.png',fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});

test('optional social slots are editable from preview, validate on publishing, and respect the block switch',async({page,request})=>{
  const slug=await createBio(page);
  await page.locator('#add-block').click();await page.locator('[data-add=social]').click();
  await page.locator('#block-details-form [name=url1]').fill('https://instagram.com/example');
  await page.locator('#confirm-add-block').click();
  const social=page.locator('[data-block-type=social]');
  await expect(page.locator('.bio-page-social a')).toHaveCount(1);
  await page.locator('#bio-preview [data-setup-social="2"]').click();
  await expect(social.locator('[data-key=url2]')).toBeFocused();
  await social.locator('[data-key=platform2]').selectOption('linkedin');
  await social.locator('[data-key=url2]').fill('javascript:alert(1)');
  await social.locator('[data-block-action=minimize]').click();
  await page.locator('#publish-bio').click();
  await expect(social.locator('[data-key=url2]')).toBeFocused();
  await expect(page.locator('.bio-page-social a')).toHaveCount(1);
  await social.locator('[data-key=url2]').fill('https://linkedin.com/in/example');
  await page.locator('[data-language=ms]').click();await expect(social.locator('h4')).toContainText('Media sosial');
  await page.locator('[data-language=en]').click();
  await page.locator('#publish-bio').click();await expect(page.locator('#bio-result')).toBeVisible();
  const html=await (await request.get('/sites/'+slug+'/')).text();
  expect(html.match(/<a class="bio-social-circle"/g)).toHaveLength(2);
  expect(html).not.toContain('<button');
  await social.getByRole('switch').click();await expect(page.locator('.bio-page-social')).toHaveCount(0);
  await page.locator('#publish-bio').click();await expect(page.locator('#bio-result')).toBeVisible();
  expect(await (await request.get('/sites/'+slug+'/')).text()).not.toContain('<nav class="bio-page-social"');
  await social.getByRole('switch').click();await expect(page.locator('.bio-page-social a')).toHaveCount(2);
  await social.locator('[data-block-action=remove]').click();
  await expect(page.locator('#bio-preview [data-setup-social]')).toHaveCount(3);
});

test('server rejects invalid social platforms, unsafe URLs and duplicate social groups',async({page,request})=>{
  const slug=await createBio(page);
  const record=await (await request.get('/api/bio-pages/'+slug)).json();
  const social={id:99,type:'social',platform1:'instagram',url1:'https://instagram.com/example',platform2:'facebook',url2:'',platform3:'tiktok',url3:''};
  const save=blocks=>request.put('/api/bio-pages/'+slug,{data:{...record,state:{...record.state,blocks:[...record.state.blocks,...blocks]},publish:false}});
  for(const url of ['javascript:alert(1)','data:text/html,hello','https://user:pass@example.com'])expect((await save([{...social,url1:url}])).status()).toBe(400);
  expect((await save([{...social,platform1:'invalid'}])).status()).toBe(400);
  expect((await save([social,{...social,id:100}])).status()).toBe(400);
  expect((await save([social])).status()).toBe(200);
});
