const { test, expect } = require('./auth-fixture');
const fs = require('node:fs/promises');
const path = require('node:path');
const { createBio, expandBlocks, addBlock } = require('./bio-helper');
async function add(page, type) {
  const block=await addBlock(page,type);
  await block.locator('[data-block-action=minimize]').click();
  return block;
}
test('blocks and images update the preview and export a complete publishable page', async ({page, request, baseURL}, info) => {
  const errors=[]; page.on('pageerror',error=>errors.push(error.message));
  const slug=await createBio(page);
  await expandBlocks(page);
  await expect(page.locator('#tool-form [name=slug]')).toHaveCount(0);
  await page.locator('[name=name]').fill('Aina Studio');
  await page.locator('[name=bio]').fill('Design, photography & everyday inspiration.');
  await page.locator('[name=photo]').setInputFiles(path.resolve('assets/zprop-tech-logo.png'));
  await expect(page.locator('.bio-avatar-image')).toBeVisible();
  await page.locator('[data-key=label]').fill('Explore my work');
  await page.locator('[data-key=url]').fill('https://example.com/portfolio');
  await (await add(page,'heading')).locator('[data-key=heading]').fill('A little about me');
  await (await add(page,'text')).locator('[data-key=text]').fill('Thoughtful spaces.\nMade with care.');
  const image=await add(page,'image');
  await image.locator('[type=file]').setInputFiles(path.resolve('assets/zprop-tech-logo.png'));
  await expect(page.locator('.bio-page-image img')).toBeVisible();
  await image.locator('[data-key=alt]').fill('ZPROP studio logo');
  await image.locator('[data-key=caption]').fill('My latest project');
  await add(page,'divider');
  await expect(page.locator('.bio-page-blocks > *')).toHaveCount(6);
  await page.locator('[data-tab=appearance]').click();
  await page.locator('[name=background]').fill('#e8eee4');
  await page.locator('[name=shape]').selectOption('pill');
  await expect(page.locator('#bio-preview')).toHaveCSS('background-color','rgb(232, 238, 228)');
  await expect(page.locator('.bio-page-link')).toHaveCSS('border-radius','40px');
  await page.locator('[data-tab=content]').click();
  await page.locator('[data-language=ms]').click();
  await expect(page.locator('[name=name]')).toHaveValue('Aina Studio');
  await expect(page.locator('.bio-page-image img')).toHaveAttribute('alt','ZPROP studio logo');
  await page.locator('[data-language=en]').click();
  const downloadPromise=page.waitForEvent('download');
  await page.locator('[data-action=downloadHtml]').click();
  const download=await downloadPromise;
  const html=await fs.readFile(await download.path(),'utf8');
  expect(html).toContain('data:image/png;base64,');
  expect(html).toContain('https://example.com/portfolio');
  expect(html).toContain('My latest project');
  expect(html).not.toContain('data-key=');
  await page.locator('#publish-bio').click();
  await expect(page.locator('#bio-result')).toBeVisible();
  await expect(page.locator('#bio-url')).toHaveText(`${baseURL}/${slug}/`);
  const response=await request.get(`/${slug}/`);
  expect(response.status()).toBe(200);expect(await response.text()).toBe(html);
  await page.evaluate(()=>{navigator.clipboard.writeText=async text=>{window.copiedBio=text;};});
  await page.locator('#copy-bio').click();
  expect(await page.evaluate(()=>window.copiedBio)).toBe(`${baseURL}/${slug}/`);
  const popupPromise=page.waitForEvent('popup');
  await page.locator('#open-bio').click();
  const popup=await popupPromise;
  await expect(popup).toHaveURL(`${baseURL}/${slug}/`);
  await expect(popup.locator('.bio-page-profile h3')).toHaveText('Aina Studio');
  await popup.close();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:`test-results/bio-builder-${info.project.name}.png`,fullPage:true});
  expect(errors).toEqual([]);
});
test('block order, duplication, removal and keyboard picker preserve edited content', async ({page}) => {
  await createBio(page);
  await expandBlocks(page);
  const heading=await add(page,'heading');
  await heading.locator('[data-key=heading]').fill('First section');
  await heading.locator('.bio-drag-handle').focus();await page.keyboard.press('ArrowUp');
  await page.keyboard.press('ArrowUp');
  await expect(page.locator('.bio-page-blocks > *').first()).toHaveText('First section');
  await page.locator('.bio-block').first().locator('[data-block-action=duplicate]').click();
  await expect(page.locator('.bio-page-heading')).toHaveCount(2);
  await page.locator('.bio-block').first().locator('[data-block-action=remove]').click();
  await expect(page.locator('.bio-page-heading')).toHaveCount(1);
  await page.locator('.bio-block').first().locator('.bio-drag-handle').focus();await page.keyboard.press('ArrowDown');
  await page.keyboard.press('ArrowDown');
  await expect(page.locator('.bio-page-blocks > *').last()).toHaveText('First section');
  await page.locator('#add-block').click();await page.keyboard.press('Escape');
  await expect(page.locator('#block-picker')).not.toBeVisible();
  await expect(page.locator('#add-block')).toBeFocused();
  for(let i=0;i<3;i++) await page.locator('.bio-block').first().locator('[data-block-action=remove]').click();
  await expect(page.locator('.bio-empty')).toBeVisible();
  await expect(page.locator('.bio-page-blocks > *')).toHaveCount(0);
});
test('unsafe links, invalid images and failed publishing have recoverable errors', async ({page}) => {
  await createBio(page);
  await expandBlocks(page);
  await page.locator('[name=name]').fill('<img src=x onerror=alert(1)>');
  await expect(page.locator('#bio-preview h3')).toHaveText('<img src=x onerror=alert(1)>');
  await page.locator('[data-key=url]').fill('javascript:alert(1)');
  await expect(page.locator('.bio-page-link')).not.toHaveAttribute('href');
  await page.locator('#publish-bio').click();
  expect(await page.locator('[data-key=url]').evaluate(input=>input.validity.valid)).toBe(false);
  await page.locator('[data-key=url]').fill('https://example.com/');
  await page.locator('#add-block').click();await page.locator('[data-add=image]').click();
  await page.locator('#block-details-form [type=file]').setInputFiles({name:'bad.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg onload="alert(1)"></svg>')});
  await page.locator('#confirm-add-block').click();
  await expect(page.locator('#block-details-status')).toContainText('Choose a valid');
  await expect(page.locator('.bio-page-image img')).toHaveCount(0);
  await expect(page.locator('[data-block-type=image]')).toHaveCount(0);
  await page.locator('#close-block-picker').click();
  await page.route('**/api/bio-pages/*',route=>route.fulfill({status:409,contentType:'application/json',body:JSON.stringify({error:'taken'})}));
  await page.locator('#publish-bio').click();
  await expect(page.locator('#tool-status')).toContainText('already taken');
  await expect(page.locator('#publish-bio')).toBeEnabled();
  await page.unroute('**/api/bio-pages/*');
  await page.locator('#publish-bio').click();
  await expect(page.locator('#bio-result')).toBeVisible();
});
