const {test,expect}=require('./auth-fixture');
const {createBio,addBlock}=require('./bio-helper');

test('block setup validates essentials, supports back and cancellation, and inserts collapsed content',async({page,request})=>{
  const slug=await createBio(page);
  await expect(page.locator('.bio-block-fields:visible')).toHaveCount(0);
  await expect(page.locator('#bio-dirty')).toBeHidden();
  await page.locator('#add-block').click();await page.locator('[data-add=text]').click();
  const details=page.locator('#block-details-form');
  await expect(details.locator('textarea')).toBeFocused();
  await page.locator('#confirm-add-block').click();
  await expect(page.locator('.bio-block')).toHaveCount(2);
  await details.locator('[name=text]').fill('   ');await page.locator('#confirm-add-block').click();
  await expect(page.locator('.bio-block')).toHaveCount(2);
  await details.locator('[name=text]').fill('Not added yet');
  await page.keyboard.press('Escape');
  await expect(page.locator('#add-block')).toBeFocused();
  await expect(page.locator('#bio-dirty')).toBeHidden();
  await page.locator('#add-block').click();await page.locator('[data-add=text]').click();
  await expect(details.locator('[name=text]')).toHaveValue('');
  await page.locator('#back-block-picker').click();await expect(page.locator('[data-add=text]')).toBeFocused();
  await page.locator('[data-add=link]').click();
  await details.locator('[name=label]').fill('My portfolio');
  for(const url of ['javascript:alert(1)','https://name:password@example.com']) {
    await details.locator('[name=url]').fill(url);await page.locator('#confirm-add-block').click();
    await expect(page.locator('.bio-block')).toHaveCount(2);
    await expect(details.locator('[name=url]')).toBeFocused();
  }
  await details.locator('[name=url]').fill('https://example.com/portfolio');
  await page.locator('#confirm-add-block').click();
  await expect(page.locator('#block-picker')).toBeHidden();
  await expect(page.locator('.bio-page-link').last()).toHaveAttribute('href','https://example.com/portfolio');
  await expect(page.locator('.bio-block').last().locator('[data-block-action=minimize]')).toBeFocused();
  await addBlock(page,'text',{text:'My story.\nA second line.'});
  await addBlock(page,'heading',{heading:'Selected work'});
  await addBlock(page,'profile',{name:'Aina'});
  await addBlock(page,'divider');
  await expect(page.locator('.bio-block-fields:visible')).toHaveCount(0);
  await expect(page.locator('.bio-page-text')).toHaveText('My story.\nA second line.');
  await page.locator('.bio-block').last().locator('[data-block-action=duplicate]').click();
  await expect(page.locator('.bio-block').last().locator('.bio-block-fields')).toBeHidden();
  await page.locator('#save-bio-draft').click();await expect(page.locator('#tool-status')).toHaveText('Draft saved.');
  const record=await (await request.get('/api/bio-pages/'+slug)).json();
  expect(record.state.blocks).toHaveLength(8);
  await page.reload();await expect(page.locator('.bio-block')).toHaveCount(8);
  await expect(page.locator('.bio-block-fields:visible')).toHaveCount(0);
});

test('image setup rejects missing and invalid images, then saves a valid image',async({page})=>{
  await createBio(page);
  await page.locator('#add-block').click();await page.locator('[data-add=image]').click();
  const input=page.locator('#block-details-form [type=file]');
  await page.locator('#confirm-add-block').click();
  await expect(input).toBeFocused();
  await expect(page.locator('[data-block-type=image]')).toHaveCount(0);
  await input.setInputFiles({name:'invalid.png',mimeType:'image/png',buffer:Buffer.from('invalid image')});
  await page.locator('#confirm-add-block').click();
  await expect(page.locator('#block-details-status')).toContainText('Choose a valid');
  await expect(page.locator('[data-block-type=image]')).toHaveCount(0);
  await input.setInputFiles(require('node:path').resolve('assets/zprop-tech-logo.png'));
  await page.locator('#confirm-add-block').click();
  await expect(page.locator('#block-picker')).toBeHidden();
  await expect(page.locator('.bio-page-image img')).toBeVisible();
  await expect(page.locator('[data-block-type=image] .bio-block-fields')).toBeHidden();
});

test('appearance templates preview, customize, localize and survive saving and publishing',async({page,request},info)=>{
  const slug=await createBio(page);
  const original=await page.locator('.bio-page-blocks').innerHTML();
  await page.locator('[data-tab=appearance]').click();
  await expect(page.locator('[data-template]')).toHaveCount(9);
  await expect(page.locator('[data-template=botanical]')).toHaveAttribute('aria-pressed','true');
  await page.locator('[data-template=rose]').focus();await page.keyboard.press('Enter');
  await expect(page.locator('[data-template=rose]')).toBeFocused();
  await expect(page.locator('[name=background]')).toHaveValue('#fff1f2');
  await expect(page.locator('[name=shape]')).toHaveValue('pill');
  await expect(page.locator('#bio-preview')).toHaveCSS('background-color','rgb(255, 241, 242)');
  await expect(page.locator('.bio-page-link')).toHaveCSS('border-radius','40px');
  expect(await page.locator('.bio-page-blocks').innerHTML()).toBe(original);
  await page.locator('[name=background]').fill('#fffafa');
  await expect(page.locator('[data-template][aria-pressed=true]')).toHaveCount(0);
  await page.locator('[data-language=ms]').click();
  await expect(page.locator('#bio-templates-title')).toHaveText('Templat permulaan');
  await expect(page.locator('[data-template=rose]')).toHaveAccessibleName('Mawar');
  await page.locator('[data-language=en]').click();
  await page.locator('[data-template=midnight]').click();
  await page.locator('#save-bio-draft').click();await expect(page.locator('#tool-status')).toHaveText('Draft saved.');
  await page.reload();await expect(page.locator('.bio-block')).toHaveCount(2);
  await page.locator('[data-tab=appearance]').click();
  await expect(page.locator('[data-template=midnight]')).toHaveAttribute('aria-pressed','true');
  await page.locator('#publish-bio').click();await expect(page.locator('#bio-result')).toBeVisible();
  const html=await (await request.get('/'+slug+'/')).text();
  expect(html).toContain('--bio-bg:#141b2d');expect(html).toContain('--bio-accent:#bfcaff');
  await expect(page.locator('.bio-phone')).not.toHaveCSS('box-shadow','none');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.locator('.bio-templates').scrollIntoViewIfNeeded();
  await page.screenshot({path:'test-results/bio-templates-'+info.project.name+'.png',fullPage:true});
  await page.evaluate(()=>document.documentElement.dataset.theme='dark');
  await page.screenshot({path:'test-results/bio-templates-dark-'+info.project.name+'.png',fullPage:true});
});
