const {test,expect}=require('./auth-fixture');
const {createBio}=require('./bio-helper');
const fs=require('node:fs/promises');
const path=require('node:path');

test('profiles can be moved, added, duplicated and removed independently, then published',async({page,request})=>{
  const slug=await createBio(page);
  const profiles=page.locator('[data-block-type=profile]');
  await profiles.locator('[data-key=name]').fill('First person');
  await profiles.locator('[data-key=bio]').fill('First introduction');
  await profiles.locator('[data-key=photo]').setInputFiles(path.resolve('assets/zprop-tech-logo.png'));
  await expect(page.locator('.bio-avatar-image')).toBeVisible();
  await profiles.locator('.bio-drag-handle').focus();await page.keyboard.press('ArrowDown');
  await expect(page.locator('.bio-page-blocks > *').first()).toHaveClass('bio-page-link');
  await expect(profiles.locator('[data-profile-thumb] img')).toBeVisible();
  await page.locator('#add-block').click();await page.locator('[data-add=profile]').click();
  await profiles.last().locator('[data-key=name]').fill('Second person');
  await profiles.last().locator('[data-key=bio]').fill('Second introduction');
  await profiles.last().locator('[data-block-action=duplicate]').click();
  await profiles.last().locator('[data-key=name]').fill('Third person');
  await expect(page.locator('.bio-page-profile h3')).toHaveText(['First person','Second person','Third person']);
  await profiles.nth(1).locator('[data-block-action=remove]').click();
  await page.locator('#save-bio-draft').click();await expect(page.locator('#tool-status')).toHaveText('Draft saved.');
  await page.reload();
  await expect(page.locator('.bio-page-profile h3')).toHaveText(['First person','Third person']);
  await expect(page.locator('.bio-page-blocks > *').first()).toHaveClass('bio-page-link');
  await expect(profiles.first().locator('[data-profile-thumb] img')).toBeVisible();
  await expect(profiles.last().locator('[data-key=bio]')).toHaveValue('Second introduction');
  await profiles.first().locator('[data-block-action=removePhoto]').click();
  await expect(page.locator('.bio-avatar-image')).toHaveCount(0);
  await page.locator('#publish-bio').click();await expect(page.locator('#bio-result')).toBeVisible();
  const html=await (await request.get(`/sites/${slug}/`)).text();
  expect(html.indexOf('<a class="bio-page-link"')).toBeLessThan(html.indexOf('<header class="bio-page-profile"'));
  expect(html).toContain('First person');expect(html).toContain('Third person');expect(html).not.toContain('Second person');
  while(await profiles.count())await profiles.first().locator('[data-block-action=remove]').click();
  await page.locator('#publish-bio').click();await expect(page.locator('#bio-dirty')).toBeHidden();
  await page.reload();await expect(page.locator('.bio-page-link')).toBeVisible();
  await expect(page.locator('.bio-page-profile')).toHaveCount(0);
  const withoutProfile=await (await request.get(`/sites/${slug}/`)).text();
  expect(withoutProfile).not.toContain('<header class="bio-page-profile"');
  expect(withoutProfile).toContain(`<title>${slug}`);
});

test('legacy saved profiles become editable blocks without losing a full page or changing its published HTML',async({page,request})=>{
  const slug=await createBio(page);
  const target=path.resolve('.generated-sites',slug,'.bio.json');
  const record=JSON.parse(await fs.readFile(target,'utf8'));
  const {schemaVersion,blocks,...style}=record.state;
  const photo='data:image/png;base64,'+(await fs.readFile('assets/zprop-tech-logo.png')).toString('base64');
  record.state={...style,name:'Legacy person',bio:'Existing introduction',photo,blocks:Array.from({length:30},(_,index)=>({id:index+1,type:'heading',heading:'Section '+index}))};
  record.html='<h1>Existing published page</h1>';
  // Simulate an existing record from the previous release in this test-owned page.
  await fs.writeFile(target,JSON.stringify(record));
  await page.reload();
  await expect(page.locator('[data-key=name]')).toHaveValue('Legacy person');
  await expect(page.locator('.bio-block')).toHaveCount(31);
  await expect(page.locator('.bio-avatar-image')).toBeVisible();
  expect(await (await request.get(`/sites/${slug}/`)).text()).toBe(record.html);
  await page.locator('[data-key=name]').fill('Updated legacy person');
  await page.locator('#save-bio-draft').click();await expect(page.locator('#tool-status')).toHaveText('Draft saved.');
  await page.reload();await expect(page.locator('[data-key=name]')).toHaveValue('Updated legacy person');
  await expect(page.locator('.bio-block')).toHaveCount(31);
  const saved=await (await request.get(`/api/bio-pages/${slug}`)).json();
  expect(saved.state.schemaVersion).toBe(2);
  expect(saved.state.blocks[0]).toMatchObject({type:'profile',name:'Updated legacy person',bio:'Existing introduction',photo});
  expect(saved.state.blocks.slice(1)).toEqual(record.state.blocks);
  const {schemaVersion:version,...withoutVersion}=saved.state;
  expect((await request.put(`/api/bio-pages/${slug}`,{data:{...saved,state:withoutVersion,publish:false}})).status()).toBe(400);
  expect(await (await request.get(`/sites/${slug}/`)).text()).toBe(record.html);
});
